# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from barista.node.v1alpha1 import node_pb2 as barista_dot_node_dot_v1alpha1_dot_node__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in barista/node/v1alpha1/node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeAgentStub:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNodeInfo = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/GetNodeInfo',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.GetNodeInfoRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.NodeInfo.FromString,
                _registered_method=True)
        self.CreateInstance = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/CreateInstance',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.CreateInstanceRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.StartInstance = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/StartInstance',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.StartInstanceRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.StopInstance = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/StopInstance',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.StopInstanceRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.PauseInstance = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/PauseInstance',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.PauseInstanceRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.ResumeInstance = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/ResumeInstance',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ResumeInstanceRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.CheckpointInstance = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/CheckpointInstance',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.CheckpointInstanceRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.DestroyInstance = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/DestroyInstance',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.DestroyInstanceRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.SetWake = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/SetWake',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.SetWakeRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Instance.FromString,
                _registered_method=True)
        self.GetInstance = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/GetInstance',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.GetInstanceRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Instance.FromString,
                _registered_method=True)
        self.ListInstances = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/ListInstances',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListInstancesRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListInstancesResponse.FromString,
                _registered_method=True)
        self.ListSnapshots = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/ListSnapshots',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListSnapshotsRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListSnapshotsResponse.FromString,
                _registered_method=True)
        self.DeleteSnapshot = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/DeleteSnapshot',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.DeleteSnapshotRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.CreateSnapshot = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/CreateSnapshot',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.CreateSnapshotRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.ForkInstance = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/ForkInstance',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ForkInstanceRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.ExportCapsule = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/ExportCapsule',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ExportCapsuleRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.ImportCapsule = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/ImportCapsule',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ImportCapsuleRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.DeleteCapsule = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/DeleteCapsule',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.DeleteCapsuleRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.GetCapsule = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/GetCapsule',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.GetCapsuleRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Capsule.FromString,
                _registered_method=True)
        self.ListCapsules = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/ListCapsules',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListCapsulesRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListCapsulesResponse.FromString,
                _registered_method=True)
        self.GetOperation = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/GetOperation',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.GetOperationRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.CancelOperation = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/CancelOperation',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.CancelOperationRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.WatchEvents = channel.unary_stream(
                '/barista.node.v1alpha1.NodeAgent/WatchEvents',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.WatchEventsRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Event.FromString,
                _registered_method=True)
        self.WatchLogs = channel.unary_stream(
                '/barista.node.v1alpha1.NodeAgent/WatchLogs',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.WatchLogsRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.LogEntry.FromString,
                _registered_method=True)
        self.Exec = channel.stream_stream(
                '/barista.node.v1alpha1.NodeAgent/Exec',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ExecFrame.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ExecFrame.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_stream(
                '/barista.node.v1alpha1.NodeAgent/ReadFile',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.FileChunk.FromString,
                _registered_method=True)
        self.WriteFile = channel.stream_unary(
                '/barista.node.v1alpha1.NodeAgent/WriteFile',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.WriteFileResponse.FromString,
                _registered_method=True)


class NodeAgentServicer:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def GetNodeInfo(self, request, context):
        """Identity & capabilities.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInstance(self, request, context):
        """Lifecycle — all mutations are async, idempotent Operations (spec §4.1).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckpointInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWake(self, request, context):
        """Arm or clear the session's one wake alarm (nap-013). Not an Operation: it
        transitions nothing, and the `Instance` it returns is what the caller just
        set, read back from the journal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstance(self, request, context):
        """Introspection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInstances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSnapshots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForkInstance(self, request, context):
        """Forks, capsules, and portability (barista-046). All mutations are async,
        idempotent Operations, consistent with the lifecycle RPCs above.

        Fork branches a retained snapshot into a new, independently owned instance
        (design D2). Capsule export/import move content-addressed snapshot state
        across compatible nodes (design D3/D4); delete is crash-safe logical
        removal (design D6). Every one of these is gated by a runtime/node
        capability and fails loudly with a portability ERROR_REASON when unmet.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportCapsule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportCapsule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCapsule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapsule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCapsules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperation(self, request, context):
        """Operations & events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOperation(self, request, context):
        """Call an in-flight operation off (barista-049): the transport for
        `OPERATION_STATE_CANCELED`, which barista-048 added to the contract while
        leaving it a state no caller could reach.

        **What it does, and what it does not.** It records the operation as
        cancelled and makes its *reported outcome* final: the executor's finalize
        cannot overwrite the answer the caller was just given, so the operation
        stays CANCELED with the reason it carries. It does **not** interrupt work
        already under way — a substrate call in flight runs to completion and its
        side effect may land after the cancellation is recorded.

        **The instance still settles where the work left it.** Cancelling moves no
        instance itself, but a finalize runs *after* the work, so the state it
        records was measured on the substrate rather than inferred from the verb: a
        cancelled Stop whose stop succeeded leaves the instance STOPPED, and one
        whose stop failed leaves it FAILED. An instance is therefore not stranded in
        the transitional state its submission wrote (STOPPING, PAUSING, …) — only
        the operation's reported outcome is protected from the late writer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchLogs(self, request, context):
        """Read the workload's substrate-owned application/serial log. This is
        deliberately separate from WatchEvents: log lines have no lifecycle cursor
        and are not copied into the operation journal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request_iterator, context):
        """Guest passthrough (Phase 1 convenience; the gateway owns this later — B25).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNodeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeInfo,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.GetNodeInfoRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.NodeInfo.SerializeToString,
            ),
            'CreateInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInstance,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.CreateInstanceRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'StartInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.StartInstance,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.StartInstanceRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'StopInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.StopInstance,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.StopInstanceRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'PauseInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseInstance,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.PauseInstanceRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'ResumeInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeInstance,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ResumeInstanceRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'CheckpointInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckpointInstance,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.CheckpointInstanceRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'DestroyInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyInstance,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.DestroyInstanceRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'SetWake': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWake,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.SetWakeRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Instance.SerializeToString,
            ),
            'GetInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstance,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.GetInstanceRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Instance.SerializeToString,
            ),
            'ListInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInstances,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListInstancesRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListInstancesResponse.SerializeToString,
            ),
            'ListSnapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSnapshots,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListSnapshotsRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListSnapshotsResponse.SerializeToString,
            ),
            'DeleteSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSnapshot,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.DeleteSnapshotRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'CreateSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSnapshot,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.CreateSnapshotRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'ForkInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.ForkInstance,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ForkInstanceRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'ExportCapsule': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportCapsule,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ExportCapsuleRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'ImportCapsule': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportCapsule,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ImportCapsuleRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'DeleteCapsule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCapsule,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.DeleteCapsuleRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'GetCapsule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapsule,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.GetCapsuleRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Capsule.SerializeToString,
            ),
            'ListCapsules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCapsules,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListCapsulesRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListCapsulesResponse.SerializeToString,
            ),
            'GetOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperation,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.GetOperationRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'CancelOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOperation,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.CancelOperationRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'WatchEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchEvents,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.WatchEventsRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Event.SerializeToString,
            ),
            'WatchLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchLogs,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.WatchLogsRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.LogEntry.SerializeToString,
            ),
            'Exec': grpc.stream_stream_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ExecFrame.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ExecFrame.SerializeToString,
            ),
            'ReadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ReadFileRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.FileChunk.SerializeToString,
            ),
            'WriteFile': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.WriteFileRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.WriteFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'barista.node.v1alpha1.NodeAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('barista.node.v1alpha1.NodeAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeAgent:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def GetNodeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/GetNodeInfo',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.GetNodeInfoRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.NodeInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/CreateInstance',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.CreateInstanceRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/StartInstance',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.StartInstanceRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/StopInstance',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.StopInstanceRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/PauseInstance',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.PauseInstanceRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/ResumeInstance',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ResumeInstanceRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckpointInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/CheckpointInstance',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.CheckpointInstanceRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/DestroyInstance',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.DestroyInstanceRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetWake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/SetWake',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.SetWakeRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Instance.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/GetInstance',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.GetInstanceRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Instance.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/ListInstances',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ListInstancesRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ListInstancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/ListSnapshots',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ListSnapshotsRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ListSnapshotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/DeleteSnapshot',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.DeleteSnapshotRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/CreateSnapshot',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.CreateSnapshotRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForkInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/ForkInstance',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ForkInstanceRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportCapsule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/ExportCapsule',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ExportCapsuleRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportCapsule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/ImportCapsule',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ImportCapsuleRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCapsule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/DeleteCapsule',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.DeleteCapsuleRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapsule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/GetCapsule',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.GetCapsuleRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Capsule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCapsules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/ListCapsules',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ListCapsulesRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ListCapsulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/GetOperation',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.GetOperationRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/CancelOperation',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.CancelOperationRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/WatchEvents',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.WatchEventsRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/WatchLogs',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.WatchLogsRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.LogEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/barista.node.v1alpha1.NodeAgent/Exec',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ExecFrame.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ExecFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/ReadFile',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ReadFileRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/barista.node.v1alpha1.NodeAgent/WriteFile',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.WriteFileRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
