# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from barista.node.v1alpha1 import node_pb2 as barista_dot_node_dot_v1alpha1_dot_node__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in barista/node/v1alpha1/node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeAgentStub:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNodeInfo = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/GetNodeInfo',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.GetNodeInfoRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.NodeInfo.FromString,
                _registered_method=True)
        self.CreateInstance = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/CreateInstance',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.CreateInstanceRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.StartInstance = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/StartInstance',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.StartInstanceRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.StopInstance = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/StopInstance',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.StopInstanceRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.PauseInstance = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/PauseInstance',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.PauseInstanceRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.ResumeInstance = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/ResumeInstance',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ResumeInstanceRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.CheckpointInstance = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/CheckpointInstance',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.CheckpointInstanceRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.DestroyInstance = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/DestroyInstance',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.DestroyInstanceRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.SetWake = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/SetWake',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.SetWakeRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Instance.FromString,
                _registered_method=True)
        self.GetInstance = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/GetInstance',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.GetInstanceRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Instance.FromString,
                _registered_method=True)
        self.ListInstances = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/ListInstances',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListInstancesRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListInstancesResponse.FromString,
                _registered_method=True)
        self.ListSnapshots = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/ListSnapshots',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListSnapshotsRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListSnapshotsResponse.FromString,
                _registered_method=True)
        self.DeleteSnapshot = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/DeleteSnapshot',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.DeleteSnapshotRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.CreateSnapshot = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/CreateSnapshot',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.CreateSnapshotRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.GetOperation = channel.unary_unary(
                '/barista.node.v1alpha1.NodeAgent/GetOperation',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.GetOperationRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
                _registered_method=True)
        self.WatchEvents = channel.unary_stream(
                '/barista.node.v1alpha1.NodeAgent/WatchEvents',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.WatchEventsRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Event.FromString,
                _registered_method=True)
        self.Exec = channel.stream_stream(
                '/barista.node.v1alpha1.NodeAgent/Exec',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ExecFrame.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ExecFrame.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_stream(
                '/barista.node.v1alpha1.NodeAgent/ReadFile',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.FileChunk.FromString,
                _registered_method=True)
        self.WriteFile = channel.stream_unary(
                '/barista.node.v1alpha1.NodeAgent/WriteFile',
                request_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.WriteFileResponse.FromString,
                _registered_method=True)


class NodeAgentServicer:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def GetNodeInfo(self, request, context):
        """Identity & capabilities.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInstance(self, request, context):
        """Lifecycle — all mutations are async, idempotent Operations (spec §4.1).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckpointInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWake(self, request, context):
        """Arm or clear the session's one wake alarm (nap-013). Not an Operation: it
        transitions nothing, and the `Instance` it returns is what the caller just
        set, read back from the journal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstance(self, request, context):
        """Introspection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInstances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSnapshots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperation(self, request, context):
        """Operations & events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request_iterator, context):
        """Guest passthrough (Phase 1 convenience; the gateway owns this later — B25).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNodeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeInfo,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.GetNodeInfoRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.NodeInfo.SerializeToString,
            ),
            'CreateInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInstance,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.CreateInstanceRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'StartInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.StartInstance,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.StartInstanceRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'StopInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.StopInstance,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.StopInstanceRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'PauseInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseInstance,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.PauseInstanceRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'ResumeInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeInstance,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ResumeInstanceRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'CheckpointInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckpointInstance,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.CheckpointInstanceRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'DestroyInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyInstance,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.DestroyInstanceRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'SetWake': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWake,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.SetWakeRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Instance.SerializeToString,
            ),
            'GetInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstance,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.GetInstanceRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Instance.SerializeToString,
            ),
            'ListInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInstances,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListInstancesRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListInstancesResponse.SerializeToString,
            ),
            'ListSnapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSnapshots,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListSnapshotsRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ListSnapshotsResponse.SerializeToString,
            ),
            'DeleteSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSnapshot,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.DeleteSnapshotRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'CreateSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSnapshot,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.CreateSnapshotRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'GetOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperation,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.GetOperationRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.SerializeToString,
            ),
            'WatchEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchEvents,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.WatchEventsRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.Event.SerializeToString,
            ),
            'Exec': grpc.stream_stream_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ExecFrame.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ExecFrame.SerializeToString,
            ),
            'ReadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.ReadFileRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.FileChunk.SerializeToString,
            ),
            'WriteFile': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.WriteFileRequest.FromString,
                    response_serializer=barista_dot_node_dot_v1alpha1_dot_node__pb2.WriteFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'barista.node.v1alpha1.NodeAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('barista.node.v1alpha1.NodeAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeAgent:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def GetNodeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/GetNodeInfo',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.GetNodeInfoRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.NodeInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/CreateInstance',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.CreateInstanceRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/StartInstance',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.StartInstanceRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/StopInstance',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.StopInstanceRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/PauseInstance',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.PauseInstanceRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/ResumeInstance',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ResumeInstanceRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckpointInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/CheckpointInstance',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.CheckpointInstanceRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/DestroyInstance',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.DestroyInstanceRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetWake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/SetWake',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.SetWakeRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Instance.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/GetInstance',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.GetInstanceRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Instance.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/ListInstances',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ListInstancesRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ListInstancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/ListSnapshots',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ListSnapshotsRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ListSnapshotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/DeleteSnapshot',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.DeleteSnapshotRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/CreateSnapshot',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.CreateSnapshotRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/GetOperation',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.GetOperationRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/WatchEvents',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.WatchEventsRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/barista.node.v1alpha1.NodeAgent/Exec',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ExecFrame.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ExecFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/barista.node.v1alpha1.NodeAgent/ReadFile',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.ReadFileRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/barista.node.v1alpha1.NodeAgent/WriteFile',
            barista_dot_node_dot_v1alpha1_dot_node__pb2.WriteFileRequest.SerializeToString,
            barista_dot_node_dot_v1alpha1_dot_node__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
