# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from barista.guest.v1alpha1 import guest_pb2 as barista_dot_guest_dot_v1alpha1_dot_guest__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in barista/guest/v1alpha1/guest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GuestAgentStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/barista.guest.v1alpha1.GuestAgent/Health',
                request_serializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.HealthRequest.SerializeToString,
                response_deserializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Exec = channel.stream_stream(
                '/barista.guest.v1alpha1.GuestAgent/Exec',
                request_serializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.ExecFrame.SerializeToString,
                response_deserializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.ExecFrame.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_stream(
                '/barista.guest.v1alpha1.GuestAgent/ReadFile',
                request_serializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.FileChunk.FromString,
                _registered_method=True)
        self.WriteFile = channel.stream_unary(
                '/barista.guest.v1alpha1.GuestAgent/WriteFile',
                request_serializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.WriteFileResponse.FromString,
                _registered_method=True)
        self.StatPath = channel.unary_unary(
                '/barista.guest.v1alpha1.GuestAgent/StatPath',
                request_serializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.StatPathRequest.SerializeToString,
                response_deserializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.StatPathResponse.FromString,
                _registered_method=True)
        self.RunHook = channel.unary_unary(
                '/barista.guest.v1alpha1.GuestAgent/RunHook',
                request_serializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.RunHookRequest.SerializeToString,
                response_deserializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.RunHookResponse.FromString,
                _registered_method=True)
        self.RunRestoreDuties = channel.unary_unary(
                '/barista.guest.v1alpha1.GuestAgent/RunRestoreDuties',
                request_serializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.RestoreDutiesRequest.SerializeToString,
                response_deserializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.RestoreDutiesResponse.FromString,
                _registered_method=True)


class GuestAgentServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunHook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunRestoreDuties(self, request, context):
        """Reseed entropy + step the clock, before POST_RESTORE (spec §7).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GuestAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.HealthRequest.FromString,
                    response_serializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.HealthResponse.SerializeToString,
            ),
            'Exec': grpc.stream_stream_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.ExecFrame.FromString,
                    response_serializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.ExecFrame.SerializeToString,
            ),
            'ReadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.ReadFileRequest.FromString,
                    response_serializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.FileChunk.SerializeToString,
            ),
            'WriteFile': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.WriteFileRequest.FromString,
                    response_serializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.WriteFileResponse.SerializeToString,
            ),
            'StatPath': grpc.unary_unary_rpc_method_handler(
                    servicer.StatPath,
                    request_deserializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.StatPathRequest.FromString,
                    response_serializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.StatPathResponse.SerializeToString,
            ),
            'RunHook': grpc.unary_unary_rpc_method_handler(
                    servicer.RunHook,
                    request_deserializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.RunHookRequest.FromString,
                    response_serializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.RunHookResponse.SerializeToString,
            ),
            'RunRestoreDuties': grpc.unary_unary_rpc_method_handler(
                    servicer.RunRestoreDuties,
                    request_deserializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.RestoreDutiesRequest.FromString,
                    response_serializer=barista_dot_guest_dot_v1alpha1_dot_guest__pb2.RestoreDutiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'barista.guest.v1alpha1.GuestAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('barista.guest.v1alpha1.GuestAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GuestAgent:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.guest.v1alpha1.GuestAgent/Health',
            barista_dot_guest_dot_v1alpha1_dot_guest__pb2.HealthRequest.SerializeToString,
            barista_dot_guest_dot_v1alpha1_dot_guest__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/barista.guest.v1alpha1.GuestAgent/Exec',
            barista_dot_guest_dot_v1alpha1_dot_guest__pb2.ExecFrame.SerializeToString,
            barista_dot_guest_dot_v1alpha1_dot_guest__pb2.ExecFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/barista.guest.v1alpha1.GuestAgent/ReadFile',
            barista_dot_guest_dot_v1alpha1_dot_guest__pb2.ReadFileRequest.SerializeToString,
            barista_dot_guest_dot_v1alpha1_dot_guest__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/barista.guest.v1alpha1.GuestAgent/WriteFile',
            barista_dot_guest_dot_v1alpha1_dot_guest__pb2.WriteFileRequest.SerializeToString,
            barista_dot_guest_dot_v1alpha1_dot_guest__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.guest.v1alpha1.GuestAgent/StatPath',
            barista_dot_guest_dot_v1alpha1_dot_guest__pb2.StatPathRequest.SerializeToString,
            barista_dot_guest_dot_v1alpha1_dot_guest__pb2.StatPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunHook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.guest.v1alpha1.GuestAgent/RunHook',
            barista_dot_guest_dot_v1alpha1_dot_guest__pb2.RunHookRequest.SerializeToString,
            barista_dot_guest_dot_v1alpha1_dot_guest__pb2.RunHookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunRestoreDuties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barista.guest.v1alpha1.GuestAgent/RunRestoreDuties',
            barista_dot_guest_dot_v1alpha1_dot_guest__pb2.RestoreDutiesRequest.SerializeToString,
            barista_dot_guest_dot_v1alpha1_dot_guest__pb2.RestoreDutiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
